version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    volumes:
      - /Users/ziz/Desktop/data/mariadb/:/var/lib/mysql/
      # - /home/maneddam/data/mariadb/:/var/lib/mysql
    ports:
      - 3306
    env_file:
      - .env
    networks:
      - mynetwork
    restart: always
  # wordpress:
  #   build: ./requirements/wordpress/
  #   image: wordpress
  #   ports:
  #     - 9000
  #   volumes:
  #     - /Users/ziz/Desktop/data/wordpress/:/var/www/html/mywebsite/
  #     # - /home/maneddam/data/wordpress/:/var/www/html/
  #   networks:
  #     - mynetwork
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mariadb
  #   restart: always

  # nginx:
  #   build: ./requirements/nginx/
  #   image: nginx
  #   ports:
  #     - 433:433
  #   # volumes:
  #   #   - /home/maneddam/data/wordpress/:/var/www/html/ # -> for linux
  #   networks:
  #     - mynetwork
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - wordpress

networks:
  mynetwork:
    driver: bridge
